version: '3.9'

services:
  mongo:
    container_name: mongo_container
    image: 'mongo'
    volumes:
      - mongo-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    networks:
      - queue-net
    env_file: 
      - ./.env.production
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile
    restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/production/Dockerfile
    ports:
      - '5173:80'
    restart: always
    env_file: 
      - ./.env.production
    depends_on:
      - server
    networks:
      - queue-net

  cache:
    container_name: cache_container
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    env_file: 
    - ./.env.production
    command: bash -c "echo 1 > /proc/sys/vm/overcommit_memory && redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - cache:/data
    networks:
      - queue-net
    privileged: true

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/development/Dockerfile
    ports:
      - '5000:5000'
      - '5555:5555'
    env_file: 
      - ./.env.production
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/package.json:/usr/src/app/package.json
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json
      - ./server/nodemon.json:/usr/src/app/nodemon.json
      - ./tsconfig.json:/usr/tsconfig.json
      - ./vision-key.json:/usr/src/app/vision-key.json
    depends_on:
      - mongo
      - cache
    networks:
      - queue-net

  worker: 
    container_name: worker
    build:
      context: ./server
      dockerfile: docker/development/Dockerfile
    env_file:
      - ./.env.production
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/package.json:/usr/src/app/package.json
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json
    depends_on:
      - server
      - cache
    networks:
      - queue-net
    command: ["sh", "-c", "npx prisma generate && npx ts-node src/workers/commentWorker.ts"]


  likeworker: 
    container_name: likeworker
    build:
      context: ./server
      dockerfile: docker/development/Dockerfile
    env_file:
      - ./.env.production
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/package.json:/usr/src/app/package.json
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json
    depends_on:
      - server
      - cache
    networks:
      - queue-net
    command: ["sh", "-c", "npx prisma generate && npx ts-node src/workers/likeWorker.ts"]

  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
      - /etc/letsencrypt/live/scoopie.manishdashsharma.site/fullchain.pem:/etc/letsencrypt/live/scoopie.manishdashsharma.site/fullchain.pem:ro
      - /etc/letsencrypt/live/scoopie.manishdashsharma.site/privkey.pem:/etc/letsencrypt/live/scoopie.manishdashsharma.site/privkey.pem:ro

      - ./nginx/certificates:/etc/nginx/certificates:rw 
    restart: always
    networks:
      - queue-net
    depends_on:
      - server
      - client

networks:
  queue-net:
    driver: bridge

volumes:
  mongo-data:
  cache:
