version: '3.9'

services:
  # mongo:
  #   container_name: mongo_container
  #   image: 'mongo'
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - queue-net
  #   env_file: 
  #     - ./.env.production
  #   command: mongod --bind_ip_all
  #   restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/production/Dockerfile
    ports:
      - '5173:80'
    restart: always
    env_file: 
      - ./.env.production
    depends_on:
      - server
    networks:
      - queue-net

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/production/Dockerfile
    ports:
      - '5000:5000'
    env_file: 
      - ./.env.production
    # depends_on:
    #   - mongo
    networks:
      - queue-net
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
      # - /etc/letsencrypt/live/test.localhost/fullchain.pem:/etc/letsencrypt/live/test.localhost/fullchain.pem:ro
      # - /etc/letsencrypt/live/test.localhost/privkey.pem:/etc/letsencrypt/live/test.localhost/privkey.pem:ro

      - ./nginx/certificates:/etc/nginx/certificates:rw 
    restart: always
    networks:
      - queue-net
    depends_on:
      - server
      - client

networks:
  queue-net:
    driver: bridge

volumes:
  mongo-data:
